# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f806f55fcf068a9b4c346b79d7bed2c80122dd0bce1ec36c0397c47d90d78fcb80c8420c569f114c436507af537e532ef5f728e741dc0bda7474153304541c5

test:
  secret_key_base: 0882dcca8771d8a07609b3f59f61785407f63688604b25c5dadf9a93f8e6048fa77c44c4045f7febd26a9879ea2533283a82ee448786fec96c49d2fb3fc07e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
